checks:
  age:
    max-age: 90
  size:
    max-size: 500
    max-layers: 20
  ports:
    allowed-ports: "@config/allowed-ports.yaml"
  registry:
    registry-policy: config/registry-policy.yaml
  root-user: {}
  secrets:
    secrets-policy: config/secrets-policy.yaml
    skip-env-vars: false
    skip-files: false
