checks:
  age:
    max-age: 90
  size:
    max-size: 500
    max-layers: 20
  ports:
    allowed-ports: [80, 443]
  registry:
    registry-policy: registry-policy.yaml
  root-user: {}
  secrets:
    secrets-policy: secrets-policy.yaml
    skip-env-vars: false
    skip-files: false
